//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnhancedLinq.Internals.Localizations {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EnhancedLinq.Internals.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Exceptions_ValueNotFound_AtIndex {
            get {
                return ResourceManager.GetString("Exceptions.ValueNotFound.AtIndex", resourceCulture);
            }
        }
        
        internal static string Exceptions_IndexOutOfRange {
            get {
                return ResourceManager.GetString("Exceptions.IndexOutOfRange", resourceCulture);
            }
        }
        
        internal static string Exceptions_Count_LessThanZero {
            get {
                return ResourceManager.GetString("Exceptions.Count.LessThanZero", resourceCulture);
            }
        }
        
        internal static string Exceptions_EnumerableSplit_Empty {
            get {
                return ResourceManager.GetString("Exceptions.EnumerableSplit.Empty", resourceCulture);
            }
        }
    }
}
